name: Update Plugin Manifest

on:
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run when plugin configs change
  push:
    branches:
      - main
    paths:
      - 'plugins/**'
      - 'scripts/**'

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # cache: 'npm'  # 暂时禁用缓存，避免需要 package-lock.json
      
      - name: Install dependencies
        run: npm install
      
      - name: Generate manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run generate
      
      - name: Validate manifest
        run: npm run validate
      
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code manifest.json || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add manifest.json
          git commit -m "chore: update plugin manifest [skip ci]"
          git push
      
      - name: Summary
        run: |
          echo "### Manifest Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.git-check.outputs.changed }}" == "true" ]; then
            echo "✅ Manifest updated successfully" >> $GITHUB_STEP_SUMMARY
          else
            echo "ℹ️ No changes detected" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Statistics:**" >> $GITHUB_STEP_SUMMARY
          echo "- Total plugins: $(jq '.statistics.totalPlugins' manifest.json)" >> $GITHUB_STEP_SUMMARY
          echo "- Verified plugins: $(jq '.statistics.verifiedPlugins' manifest.json)" >> $GITHUB_STEP_SUMMARY
          echo "- Last updated: $(jq -r '.lastUpdated' manifest.json)" >> $GITHUB_STEP_SUMMARY

